spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/beatmanagement-central
      username: postgres
      password: postgres
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource

  #  flyway:
  #    baseline-on-migrate: true
  #    clean-on-validation-error: true

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

#  redis:
#    database: 0
#    host: localhost
#    port: 6379

#  logging.level: INFO

server:
  port: 8080

logging:
  level:
    org.jooq: ERROR
    jarvis.central.controller: INFO
    jarvis.central.dao: INFO
    jarvis.central.service: INFO

#management:
#  Endpoints:
#    enabled-by-default: true
#    web:
#      exposure:
#        include:

#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
